"""add_data_ingestion_scheduling

Revision ID: 3375de8c53eb
Revises: db381a28d2ec
Create Date: 2026-01-13 05:34:30.393337

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3375de8c53eb'
down_revision = 'db381a28d2ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source_configs',
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('api_key', sa.String(length=500), nullable=True),
    sa.Column('api_secret', sa.String(length=500), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('rate_limit_per_hour', sa.Integer(), nullable=True),
    sa.Column('auth_type', sa.String(length=50), nullable=True),
    sa.Column('auth_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_successful_connection', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('documentation_url', sa.String(length=500), nullable=True),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_source_configs_is_active'), 'data_source_configs', ['is_active'], unique=False)
    op.create_index(op.f('ix_data_source_configs_source_name'), 'data_source_configs', ['source_name'], unique=True)
    op.create_table('ingestion_logs',
    sa.Column('dataset_version_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('records_fetched', sa.Integer(), nullable=True),
    sa.Column('records_added', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('records_skipped', sa.Integer(), nullable=True),
    sa.Column('checksum_before', sa.String(length=64), nullable=True),
    sa.Column('checksum_after', sa.String(length=64), nullable=True),
    sa.Column('has_changes', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_traceback', sa.Text(), nullable=True),
    sa.Column('ingestion_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_logs_status'), 'ingestion_logs', ['status'], unique=False)
    # op.drop_table('spatial_ref_sys')  # REMOVED: PostGIS system table
    op.add_column('dataset_versions', sa.Column('last_checked_at', sa.DateTime(), nullable=True))
    op.add_column('dataset_versions', sa.Column('last_updated_at', sa.DateTime(), nullable=True))
    op.add_column('dataset_versions', sa.Column('next_check_at', sa.DateTime(), nullable=True))
    op.add_column('dataset_versions', sa.Column('check_enabled', sa.Boolean(), nullable=True))
    op.add_column('dataset_versions', sa.Column('source_reliability_score', sa.Float(), nullable=True))
    op.add_column('dataset_versions', sa.Column('consecutive_failures', sa.Integer(), nullable=True))
    op.add_column('dataset_versions', sa.Column('last_error', sa.Text(), nullable=True))
    op.add_column('dataset_versions', sa.Column('last_ingestion_duration_seconds', sa.Float(), nullable=True))
    op.add_column('dataset_versions', sa.Column('last_records_added', sa.Integer(), nullable=True))
    op.add_column('dataset_versions', sa.Column('last_records_updated', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_dataset_versions_check_enabled'), 'dataset_versions', ['check_enabled'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dataset_versions_check_enabled'), table_name='dataset_versions')
    op.drop_column('dataset_versions', 'last_records_updated')
    op.drop_column('dataset_versions', 'last_records_added')
    op.drop_column('dataset_versions', 'last_ingestion_duration_seconds')
    op.drop_column('dataset_versions', 'last_error')
    op.drop_column('dataset_versions', 'consecutive_failures')
    op.drop_column('dataset_versions', 'source_reliability_score')
    op.drop_column('dataset_versions', 'check_enabled')
    op.drop_column('dataset_versions', 'next_check_at')
    op.drop_column('dataset_versions', 'last_updated_at')
    op.drop_column('dataset_versions', 'last_checked_at')
    # op.create_table('spatial_ref_sys',  # REMOVED: PostGIS system table
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    op.drop_index(op.f('ix_ingestion_logs_status'), table_name='ingestion_logs')
    op.drop_table('ingestion_logs')
    op.drop_index(op.f('ix_data_source_configs_source_name'), table_name='data_source_configs')
    op.drop_index(op.f('ix_data_source_configs_is_active'), table_name='data_source_configs')
    op.drop_table('data_source_configs')
    # ### end Alembic commands ###
