"""Add post-MVP verticals and multi-source support

Revision ID: db381a28d2ec
Revises: 
Create Date: 2026-01-13 04:54:16.109336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db381a28d2ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_sectors',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_fr', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_sectors_name'), 'business_sectors', ['name'], unique=True)
    op.create_table('job_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_fr', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_categories_name'), 'job_categories', ['name'], unique=True)
    op.create_table('property_types',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_fr', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_types_name'), 'property_types', ['name'], unique=True)
    op.create_table('business_stats',
    sa.Column('commune_id', sa.Integer(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=True),
    sa.Column('num_businesses', sa.Integer(), nullable=True),
    sa.Column('num_new_businesses', sa.Integer(), nullable=True),
    sa.Column('num_closed_businesses', sa.Integer(), nullable=True),
    sa.Column('business_birth_rate', sa.Float(), nullable=True),
    sa.Column('business_death_rate', sa.Float(), nullable=True),
    sa.Column('total_revenue', sa.Float(), nullable=True),
    sa.Column('avg_revenue_per_business', sa.Float(), nullable=True),
    sa.Column('total_employees', sa.Integer(), nullable=True),
    sa.Column('avg_employees_per_business', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('micro_businesses', sa.Integer(), nullable=True),
    sa.Column('small_businesses', sa.Integer(), nullable=True),
    sa.Column('medium_businesses', sa.Integer(), nullable=True),
    sa.Column('large_businesses', sa.Integer(), nullable=True),
    sa.Column('formal_businesses', sa.Integer(), nullable=True),
    sa.Column('informal_businesses', sa.Integer(), nullable=True),
    sa.Column('formality_rate', sa.Float(), nullable=True),
    sa.Column('data_quality_score', sa.Float(), nullable=True),
    sa.Column('is_estimated', sa.Boolean(), nullable=True),
    sa.Column('business_density_index', sa.Float(), nullable=True),
    sa.Column('sector_growth_score', sa.Float(), nullable=True),
    sa.Column('economic_resilience_index', sa.Float(), nullable=True),
    sa.Column('market_gap_indicator', sa.Float(), nullable=True),
    sa.Column('competition_intensity', sa.String(length=20), nullable=True),
    sa.Column('market_saturation', sa.String(length=20), nullable=True),
    sa.Column('innovation_score', sa.Float(), nullable=True),
    sa.Column('digital_adoption_rate', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['commune_id'], ['communes.id'], ),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['business_sectors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commune_id', 'sector_id', 'year', 'quarter', name='uq_commune_sector_year_quarter')
    )
    op.create_index('idx_commune_year_biz', 'business_stats', ['commune_id', 'year'], unique=False)
    op.create_index('idx_sector_year', 'business_stats', ['sector_id', 'year'], unique=False)
    op.create_index(op.f('ix_business_stats_commune_id'), 'business_stats', ['commune_id'], unique=False)
    op.create_index(op.f('ix_business_stats_sector_id'), 'business_stats', ['sector_id'], unique=False)
    op.create_index(op.f('ix_business_stats_year'), 'business_stats', ['year'], unique=False)
    op.create_table('employment_stats',
    sa.Column('commune_id', sa.Integer(), nullable=False),
    sa.Column('job_category_id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=True),
    sa.Column('total_employed', sa.Integer(), nullable=True),
    sa.Column('total_unemployed', sa.Integer(), nullable=True),
    sa.Column('labor_force', sa.Integer(), nullable=True),
    sa.Column('unemployment_rate', sa.Float(), nullable=True),
    sa.Column('participation_rate', sa.Float(), nullable=True),
    sa.Column('informal_employed', sa.Integer(), nullable=True),
    sa.Column('informal_rate', sa.Float(), nullable=True),
    sa.Column('median_salary', sa.Float(), nullable=True),
    sa.Column('min_salary', sa.Float(), nullable=True),
    sa.Column('max_salary', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('youth_employment', sa.Integer(), nullable=True),
    sa.Column('female_employment', sa.Integer(), nullable=True),
    sa.Column('data_quality_score', sa.Float(), nullable=True),
    sa.Column('is_estimated', sa.Boolean(), nullable=True),
    sa.Column('job_category_label', sa.String(length=50), nullable=True),
    sa.Column('skill_level_index', sa.Float(), nullable=True),
    sa.Column('employment_pressure_index', sa.Float(), nullable=True),
    sa.Column('informality_rate_index', sa.Float(), nullable=True),
    sa.Column('salary_range_estimation', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['commune_id'], ['communes.id'], ),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['job_category_id'], ['job_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commune_id', 'job_category_id', 'year', 'quarter', name='uq_commune_job_year_quarter')
    )
    op.create_index('idx_commune_year_emp', 'employment_stats', ['commune_id', 'year'], unique=False)
    op.create_index('idx_job_year', 'employment_stats', ['job_category_id', 'year'], unique=False)
    op.create_index(op.f('ix_employment_stats_commune_id'), 'employment_stats', ['commune_id'], unique=False)
    op.create_index(op.f('ix_employment_stats_job_category_id'), 'employment_stats', ['job_category_id'], unique=False)
    op.create_index(op.f('ix_employment_stats_year'), 'employment_stats', ['year'], unique=False)
    op.create_table('real_estate_stats',
    sa.Column('commune_id', sa.Integer(), nullable=False),
    sa.Column('property_type_id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=True),
    sa.Column('median_price', sa.Float(), nullable=True),
    sa.Column('price_per_sqm', sa.Float(), nullable=True),
    sa.Column('min_price', sa.Float(), nullable=True),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('num_transactions', sa.Integer(), nullable=True),
    sa.Column('transaction_volume', sa.Float(), nullable=True),
    sa.Column('inventory_count', sa.Integer(), nullable=True),
    sa.Column('days_on_market', sa.Float(), nullable=True),
    sa.Column('rental_yield', sa.Float(), nullable=True),
    sa.Column('data_quality_score', sa.Float(), nullable=True),
    sa.Column('is_estimated', sa.Boolean(), nullable=True),
    sa.Column('property_type_label', sa.String(length=50), nullable=True),
    sa.Column('geo_zone', sa.String(length=50), nullable=True),
    sa.Column('price_per_sqm_index', sa.Float(), nullable=True),
    sa.Column('price_trend', sa.String(length=20), nullable=True),
    sa.Column('land_risk_level', sa.String(length=20), nullable=True),
    sa.Column('infrastructure_score', sa.Float(), nullable=True),
    sa.Column('legal_clarity_index', sa.Float(), nullable=True),
    sa.Column('development_potential', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['commune_id'], ['communes.id'], ),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['property_type_id'], ['property_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commune_id', 'property_type_id', 'year', 'quarter', name='uq_commune_property_year_quarter')
    )
    op.create_index('idx_commune_year_re', 'real_estate_stats', ['commune_id', 'year'], unique=False)
    op.create_index('idx_property_year', 'real_estate_stats', ['property_type_id', 'year'], unique=False)
    op.create_index(op.f('ix_real_estate_stats_commune_id'), 'real_estate_stats', ['commune_id'], unique=False)
    op.create_index(op.f('ix_real_estate_stats_property_type_id'), 'real_estate_stats', ['property_type_id'], unique=False)
    op.create_index(op.f('ix_real_estate_stats_year'), 'real_estate_stats', ['year'], unique=False)
    op.create_table('agri_stats_source_contributions',
    sa.Column('agri_stat_id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('contribution_weight', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('source_value', sa.Float(), nullable=True),
    sa.Column('deviation_from_final', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agri_stat_id'], ['agri_stats.id'], ),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agri_stat_id', 'data_source_id', name='uq_agristat_source')
    )
    op.create_index('idx_agristat_source', 'agri_stats_source_contributions', ['agri_stat_id', 'data_source_id'], unique=False)
    op.create_index(op.f('ix_agri_stats_source_contributions_agri_stat_id'), 'agri_stats_source_contributions', ['agri_stat_id'], unique=False)
    op.create_index(op.f('ix_agri_stats_source_contributions_data_source_id'), 'agri_stats_source_contributions', ['data_source_id'], unique=False)
    op.create_table('business_source_contributions',
    sa.Column('business_stat_id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('contribution_weight', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('source_value', sa.Float(), nullable=True),
    sa.Column('deviation_from_final', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_stat_id'], ['business_stats.id'], ),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_stat_id', 'data_source_id', name='uq_business_source')
    )
    op.create_index('idx_business_source', 'business_source_contributions', ['business_stat_id', 'data_source_id'], unique=False)
    op.create_index(op.f('ix_business_source_contributions_business_stat_id'), 'business_source_contributions', ['business_stat_id'], unique=False)
    op.create_index(op.f('ix_business_source_contributions_data_source_id'), 'business_source_contributions', ['data_source_id'], unique=False)
    op.create_table('employment_source_contributions',
    sa.Column('employment_stat_id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('contribution_weight', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('source_value', sa.Float(), nullable=True),
    sa.Column('deviation_from_final', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['employment_stat_id'], ['employment_stats.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employment_stat_id', 'data_source_id', name='uq_employment_source')
    )
    op.create_index('idx_employment_source', 'employment_source_contributions', ['employment_stat_id', 'data_source_id'], unique=False)
    op.create_index(op.f('ix_employment_source_contributions_data_source_id'), 'employment_source_contributions', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_employment_source_contributions_employment_stat_id'), 'employment_source_contributions', ['employment_stat_id'], unique=False)
    op.create_table('real_estate_source_contributions',
    sa.Column('real_estate_stat_id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('contribution_weight', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('source_value', sa.Float(), nullable=True),
    sa.Column('deviation_from_final', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['real_estate_stat_id'], ['real_estate_stats.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('real_estate_stat_id', 'data_source_id', name='uq_realestate_source')
    )
    op.create_index('idx_realestate_source', 'real_estate_source_contributions', ['real_estate_stat_id', 'data_source_id'], unique=False)
    op.create_index(op.f('ix_real_estate_source_contributions_data_source_id'), 'real_estate_source_contributions', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_real_estate_source_contributions_real_estate_stat_id'), 'real_estate_source_contributions', ['real_estate_stat_id'], unique=False)
    # REMOVED: op.drop_table('spatial_ref_sys') - PostGIS system table, should not be dropped
    op.add_column('agri_stats', sa.Column('crop_type', sa.String(length=50), nullable=True))
    op.add_column('agri_stats', sa.Column('geo_zone', sa.String(length=50), nullable=True))
    op.add_column('agri_stats', sa.Column('climate_risk_level', sa.String(length=20), nullable=True))
    op.add_column('agri_stats', sa.Column('soil_quality_index', sa.Float(), nullable=True))
    op.add_column('agri_stats', sa.Column('yield_estimation_class', sa.String(length=20), nullable=True))
    op.add_column('agri_stats', sa.Column('price_volatility_index', sa.Float(), nullable=True))
    op.add_column('agri_stats', sa.Column('mechanization_level', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agri_stats', 'mechanization_level')
    op.drop_column('agri_stats', 'price_volatility_index')
    op.drop_column('agri_stats', 'yield_estimation_class')
    op.drop_column('agri_stats', 'soil_quality_index')
    op.drop_column('agri_stats', 'climate_risk_level')
    op.drop_column('agri_stats', 'geo_zone')
    op.drop_column('agri_stats', 'crop_type')
    # REMOVED: op.create_table('spatial_ref_sys', ...) - PostGIS system table, should not be recreated
    op.drop_index(op.f('ix_real_estate_source_contributions_real_estate_stat_id'), table_name='real_estate_source_contributions')
    op.drop_index(op.f('ix_real_estate_source_contributions_data_source_id'), table_name='real_estate_source_contributions')
    op.drop_index('idx_realestate_source', table_name='real_estate_source_contributions')
    op.drop_table('real_estate_source_contributions')
    op.drop_index(op.f('ix_employment_source_contributions_employment_stat_id'), table_name='employment_source_contributions')
    op.drop_index(op.f('ix_employment_source_contributions_data_source_id'), table_name='employment_source_contributions')
    op.drop_index('idx_employment_source', table_name='employment_source_contributions')
    op.drop_table('employment_source_contributions')
    op.drop_index(op.f('ix_business_source_contributions_data_source_id'), table_name='business_source_contributions')
    op.drop_index(op.f('ix_business_source_contributions_business_stat_id'), table_name='business_source_contributions')
    op.drop_index('idx_business_source', table_name='business_source_contributions')
    op.drop_table('business_source_contributions')
    op.drop_index(op.f('ix_agri_stats_source_contributions_data_source_id'), table_name='agri_stats_source_contributions')
    op.drop_index(op.f('ix_agri_stats_source_contributions_agri_stat_id'), table_name='agri_stats_source_contributions')
    op.drop_index('idx_agristat_source', table_name='agri_stats_source_contributions')
    op.drop_table('agri_stats_source_contributions')
    op.drop_index(op.f('ix_real_estate_stats_year'), table_name='real_estate_stats')
    op.drop_index(op.f('ix_real_estate_stats_property_type_id'), table_name='real_estate_stats')
    op.drop_index(op.f('ix_real_estate_stats_commune_id'), table_name='real_estate_stats')
    op.drop_index('idx_property_year', table_name='real_estate_stats')
    op.drop_index('idx_commune_year_re', table_name='real_estate_stats')
    op.drop_table('real_estate_stats')
    op.drop_index(op.f('ix_employment_stats_year'), table_name='employment_stats')
    op.drop_index(op.f('ix_employment_stats_job_category_id'), table_name='employment_stats')
    op.drop_index(op.f('ix_employment_stats_commune_id'), table_name='employment_stats')
    op.drop_index('idx_job_year', table_name='employment_stats')
    op.drop_index('idx_commune_year_emp', table_name='employment_stats')
    op.drop_table('employment_stats')
    op.drop_index(op.f('ix_business_stats_year'), table_name='business_stats')
    op.drop_index(op.f('ix_business_stats_sector_id'), table_name='business_stats')
    op.drop_index(op.f('ix_business_stats_commune_id'), table_name='business_stats')
    op.drop_index('idx_sector_year', table_name='business_stats')
    op.drop_index('idx_commune_year_biz', table_name='business_stats')
    op.drop_table('business_stats')
    op.drop_index(op.f('ix_property_types_name'), table_name='property_types')
    op.drop_table('property_types')
    op.drop_index(op.f('ix_job_categories_name'), table_name='job_categories')
    op.drop_table('job_categories')
    op.drop_index(op.f('ix_business_sectors_name'), table_name='business_sectors')
    op.drop_table('business_sectors')
    # ### end Alembic commands ###
